### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by JacobWasFramed** [cgarwood/mpc-control#12]
I'm not sure the cause of the crashing. It appears it may be an issue with telnet? I'm a noob when it comes to node and advance javascript. Here's the log. It'll run fine for a few hours then just randomly crash without interaction. I've tried to use the autorestart launcher, but the script doesn't always seem to catch the crash so I end up with an unresponsive server either way.

```
>> QLActive
>> IsMXRun
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Cannot connect)
    at Telnet.emit (events.js:171:17)
    at Socket.socket.setTimeout (D:\mpc-control-master\node_modules\telnet-client\lib\index.js:76:16)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:448:8)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)

D:\mpc-control-master>
```

**Comment by JacobWasFramed** [comment]
I'm not sure where I should begin troubleshooting this. If you guys have any pointers, I can look into this further and see what I can uncover. From what I can decipher, it appears that theres is a connection issue with Telnet so I'm not sure if I need to configure mx manager differently, or if I can change the timeout setting to be a bit longer?

**Comment by cgarwood** [comment]
Are you running the mpc-control server on the same system that MxManager is running on? It does look like something is causing the connection to be interrupted or time out and it's not reconnecting.

@jay-oswald any thoughts? Not sure if it would be related to any of the telnet handling changes you made a while back? I never have actually updated the codebase on my setup at church to do any additional testing yet.

**Comment by JacobWasFramed** [comment]
It is running on the lighting PC. I can run it on a dedicated machine if you think that may help? I didn't think it would though since it'd be a hop away. There might be more potential issues with that setup vs running it on the same machine. I'm up to try anything though.

**Comment by JacobWasFramed** [comment]
I just tried to run it again, and it was running for about 30 minutes or so, I refreshed the page and got another crash. This one was slightly different, but seems to stem from another function in the events.js. I'm not sure if this is a Node issue or if it's something with mpc-control.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
Emitted 'error' event at:
    at WebSocket.finalize (D:\mpc-control-master\node_modules\ws\lib\WebSocket.js:182:41)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by JacobWasFramed** [comment]
So I found events.js in the node modules and it appears that the function that ends at line 167 is within the function that ends on line 173, so it may be related. This is the function. Is there anything that calls on this function that would cause it to error?


```
154. EventEmitter.prototype.once = function(type, listener) {
155.   if (!isFunction(listener))
156.     throw TypeError('listener must be a function');
157. 
158.   var fired = false;
159. 
160.   function g() {
161.     this.removeListener(type, g);
162. 
163.     if (!fired) {
164.       fired = true;
165.       listener.apply(this, arguments);
166.     }
167.   }
168. 
169.   g.listener = listener;
170.   this.on(type, g);
171.
172.  return this;
173. };
```

**Comment by JacobWasFramed** [comment]
So reading up, it appears this sort of thing happens when an error is thrown but there’s not a listener to catch it and do something with it. I found one thing about using pm2 to launch the server and it will keep it alive even with unhandled errors. I’m going to try that and report back.

**Comment by jay-oswald** [comment]
@cgarwood @JacobWasFramed 

Oops, missed this earlier with my flood of GitHub I get for work haha

pm2 works well, but is slightly more complicated, I personally use it for all my professional code in production, but for this little app to make it more accessable theres the autostart.bat file, which you can use on windows to auto-restart it.

If you want to use pm2 instead I could add it and put in the small startup scrips, it is a much better solution

**Comment by JacobWasFramed** [comment]
I had been using the auto restart script and it worked most of the time, but there would still be instances where it would crash and not restart, and with it not having any sort of cli feedback aside from “server started” I wanted to see what was causing it to crash. We just got a fire tablet in from amazon so my goal is to have everything up and running by the end of today.

**Comment by jay-oswald** [comment]
@JacobWasFramed added very basic pm2 as a PR #13 will need to wait for @cgarwood to review and accept, but theres only a few lines changed, you can just copy and paste yourself

**Comment by cgarwood** [comment]
Merged 👍

**Comment by JacobWasFramed** [comment]
I'll give it a shot! Thanks!

**Comment by JacobWasFramed** [comment]
Pm2 seems to have gotten a handle on the issue as the program continues to run. It does report that it has restarted twice, but I haven't noticed any issues with the tablet reconnecting. I'll close this for now, although I'm not sure why it is not handling errors appropriately.
