### ISSUE TITLE
Cycle through cuelist

### ISSUE THREAD

**Issue by JacobWasFramed** [cgarwood/mpc-control#14]
Not necessarily an issue, but a question. I have one cuelist that I would like to cycle through as it changes the color of the fixtures on set, however I can only seem to toggle cues on and off. Is there a method to just send a "Go" command every time on a certain cue instead of the go/release?

Thanks!

**Comment by jay-oswald** [comment]
This could be done, and handled by vue, however it is not currently a feature, the top on my list is faders, and i have them working apppart from a few bugs, then that sounds usefull.

Just to clarify, you mean have 1 button that cycles through a list of Cue's? so it would have like `[1,2,3,4,5]` and when you press it then it checks which cue is active then goes to the next one in the array, if none are active it goes to the begining, and it also loops through, so if your on 5 and you press it then it goes back to 1?

**Comment by JacobWasFramed** [comment]
Essentially, I would just have it cycle through a native cuelist in mpc. The way I see it, if we were to add a data attribute tag to each button we could specify whether it was a toggle or if it was simply a go button. I actually thought that this was how mpc-control worked already (simply firing a go command) as I had set in mpc to release the cue on next go on my cuelists with one single cue, but I found out that mpc-control didn’t work that way when I tried to fire off a cuelist with multiple cues. It would fire the first cue then release on next go. For the simplicity of getting it setup, it makes perfect sense to do the toggle. I’ll look at seeing if I can implement that sort of thing on Saturday. I have some background in web development with HTML and JavaScript, but and new to Node, but I think I should be able to figure this one out. If I can get it working cleanly I’ll fork and commit the code for review.

**Comment by jay-oswald** [comment]
The best way to do this IMO would be an array, so if the variable passed is a number, it toggles it on and off, but if you pass an array it cycles through the cues?

**Comment by JacobWasFramed** [comment]
added the ability to define a method. The default of toggle or the option of list. Tested and is working. Created pull request.

**Comment by JacobWasFramed** [comment]
Merged.
