### ISSUE TITLE
Server crashes on reload

### ISSUE THREAD

**Issue by jay-oswald** [cgarwood/mpc-control#9]
I've had a problem of the server crashing on reload, every time I reload the page, it crashes the server. Its why I did PR #7 for auto-restart to at least keep it working when it does happen rather then having to restart the server.

No idea why its crashing in the first place, haven't looked into it at all.

**Comment by JacobWasFramed** [comment]
I just put in a pull request that addresses this issue. It was due to the open websocket throwing an error when the client is refreshing. I added an error handler function and it seems to have resolved this issue.

**Comment by cgarwood** [comment]
Patch merged in #16
